### ISSUE TITLE
Missing API endpoints

### ISSUE THREAD

**Issue by YuXiaoCoder** [0xFacet/ethscriptions-indexer#11]
Missing API endpoints that prevent alignment with official nodes(`https://api.ethscriptions.com/api`)
1. `/block_status/`: `https://docs.ethscriptions.com/api-docs/indexer-status-endpoints`
2. `/ethscriptions/newer_ethscriptions`: `https://github.com/0xFacet/facet-vm/blob/main/app/models/ethscription_sync.rb`

**Comment by RogerPodacter** [comment]
I'm adding these in https://github.com/0xFacet/ethscriptions-indexer/pull/9, though I am renaming `block_status` to just `status`.

There's a corresponding PR https://github.com/0xFacet/facet-vm/pull/159 on the VM to become compatible with these changes.

As part of this we're upgrading the syncing to use a full checksum to verify the indexers are in the same state versus a simple count as we are currently doing.

**Comment by RogerPodacter** [comment]
I just merged it! Try out the new endpoints and let me know what you think!

**Comment by YuXiaoCoder** [comment]
@RogerPodacter 
```bash
NoMethodError (undefined method `get_block_number' for #<UniversalClient:0x00007f52b8077008 @base_url="http://eth-2.eth.blocknodehub.com:8545", @api_key="Placeholder">):

app/models/eth_block.rb:190:in `uncached_global_block_number'
app/models/eth_block.rb:195:in `block in cached_global_block_number'
app/models/eth_block.rb:194:in `cached_global_block_number'
app/controllers/status_controller.rb:3:in `indexer_status'
```

**Comment by RogerPodacter** [comment]
Ah yes my apologies! What is the right way to implement that? It’s on
alchemy already

**Comment by YuXiaoCoder** [comment]
@RogerPodacter It's pretty simple, just missed adding the get_block_number method for UniversalClient
https://github.com/0xFacet/ethscriptions-indexer/pull/16

**Comment by RogerPodacter** [comment]
Merged! Thank you!!
